// Library of 366 Motivational Fitness & Discipline Quotes in Spanish
// One quote for each day of the year (including leap years)
const MOTIVATIONAL_QUOTES_366 = [
    "El único entrenamiento malo es el que no se hizo.",
    "La fuerza no viene de la capacidad física, sino de una voluntad indomable. - Mahatma Gandhi",
    "Tu cuerpo puede soportar casi cualquier cosa, es a tu mente a la que tienes que convencer.",
    "No te compares con los demás. Compárate con la persona que eras ayer.",
    "La disciplina es hacer lo que debes hacer, incluso cuando no quieres hacerlo.",
    "Cada entrenamiento cuenta. Escribe tu historia repetición tras repetición.",
    "Tus límites actuales están esperando a ser superados.",
    "Ciencia, constancia y sudor. No hay secretos ni atajos hacia el éxito.",
    "El dolor del entrenamiento es temporal, el orgullo de haberlo logrado es para siempre.",
    "Los campeones no se hacen en los gimnasios. Se hacen con algo que tienen en su interior: un deseo, un sueño, una visión. - Muhammad Ali",
    "La constancia vence a la genética y al talento.",
    "No te detengas cuando te canses, deténte cuando hayas terminado.",
    "Si fuera fácil, todo el mundo lo haría.",
    "El éxito en el fitness es la suma de pequeños esfuerzos repetidos día tras día.",
    "Tu salud es una inversión, no un gasto.",
    "El cuerpo logra lo que la mente cree.",
    "No busques excusas, busca resultados.",
    "Hoy haré lo que otros no harán, para que mañana pueda hacer lo que otros no pueden. - Jerry Rice",
    "El músculo más fuerte es la voluntad.",
    "La diferencia entre lo imposible y lo posible radica en la determinación de una persona. - Tommy Lasorda",
    "El sudor es la grasa llorando.",
    "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
    "Cada repetición te acerca más a tu mejor versión.",
    "El único límite para nuestro logro de mañana serán nuestras dudas de hoy. - Franklin D. Roosevelt",
    "La fuerza física se mide por lo que el cuerpo puede cargar. La fuerza mental por lo que puede soportar.",
    "El cambio comienza en tu mente.",
    "No te quejes del dolor, disfrútalo; significa que tus músculos están creciendo.",
    "Tus excusas no queman calorías.",
    "Hazlo por ti, no por los demás.",
    "El éxito no es para los que lo desean, es para los que trabajan por él.",
    "Un año a partir de ahora, desearás haber comenzado hoy. - Karen Lamb",
    "La motivación te pone en marcha, el hábito te mantiene en el camino.",
    "Si no te desafía, no te cambia.",
    "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente. - Henry Ford",
    "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
    "Tu actitud determina tu dirección.",
    "La mayor recompensa de tu esfuerzo no es lo que obtienes, sino en quién te conviertes.",
    "Toda meta comienza con la decisión de intentarlo.",
    "Los resultados tardan en llegar, pero el esfuerzo da sus frutos cada día.",
    "El gimnasio es el templo de la autodisciplina.",
    "Cada día es una nueva oportunidad para ser más fuerte.",
    "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer. - John Wooden",
    "El secreto para salir adelante es comenzar.",
    "Tu mente se rendirá mil veces antes de que tu cuerpo lo haga. Sigue adelante.",
    "La fuerza no proviene de ganar. Tus luchas desarrollan tus fortalezas. - Arnold Schwarzenegger",
    "Un cuerpo sano es la base de una mente brillante.",
    "La pereza es la enemiga de tus sueños.",
    "No te conformes con lo que necesitas, lucha por lo que mereces.",
    "Cada gota de sudor te acerca un paso más al éxito.",
    "El obstáculo es el camino. - Marco Aurelio",
    "La fatiga es mental, el cuerpo tiene energía de sobra.",
    "No sueñes con entrenar bien, hazlo realidad.",
    "La disciplina te llevará a lugares donde la motivación no puede.",
    "El éxito es el resultado de la preparación, el trabajo duro y el aprendizaje del fracaso.",
    "Sé más fuerte que tus excusas.",
    "El esfuerzo de hoy es el orgullo del mañana.",
    "No compitas con nadie más que contigo mismo.",
    "La energía y la persistencia conquistan todas las cosas. - Benjamin Franklin",
    "La salud no lo es todo, pero sin ella, todo lo demás es nada.",
    "Acepta el desafío y supera tus límites.",
    "Céntrate en el proceso, los resultados vendrán solos.",
    "El dolor que sientes hoy será la fuerza que sientas mañana.",
    "La constancia es la clave que abre todas las puertas del éxito.",
    "El único día malo es el que decides no dar el máximo de ti.",
    "Tu cuerpo es tu máquina más valiosa; cuídala.",
    "No te rindas nunca. Las grandes cosas llevan tiempo.",
    "El compromiso es lo que transforma una promesa en realidad.",
    "Entrenar es un acto de amor propio.",
    "El camino hacia el éxito está lleno de baches, pero vale la pena recorrerlo.",
    "Sé la mejor versión de ti mismo en cada entrenamiento.",
    "La mente domina al cuerpo; nunca lo olvides.",
    "La fuerza está en la mente, el cuerpo solo sigue las órdenes.",
    "El éxito se mide por cuántas veces te levantas después de caer.",
    "Tu objetivo debe ser superar tus marcas del mes pasado.",
    "El entrenamiento es la cura para el estrés y la duda.",
    "No busques el camino fácil; busca el camino que te haga fuerte.",
    "La consistencia vence a la intensidad a largo plazo.",
    "Cree que puedes y ya habrás recorrido la mitad del camino. - Theodore Roosevelt",
    "El cansancio es temporal, la satisfacción es permanente.",
    "Cada paso cuenta, por pequeño que sea.",
    "La fuerza de voluntad es el motor que te lleva a la meta.",
    "No dejes para mañana el entrenamiento que puedes disfrutar hoy.",
    "La autodisciplina es el puente entre las metas y los logros.",
    "Tu cuerpo refleja tu estilo de vida.",
    "No dejes que el miedo a fallar te impida intentar.",
    "El gimnasio es donde esculpes tu destino físico.",
    "Toma el control de tu salud hoy mismo.",
    "El esfuerzo continuo, no la fuerza o la inteligencia, es la clave para liberar nuestro potencial. - Winston Churchill",
    "Cada sesión de entrenamiento es una victoria sobre la pereza.",
    "La salud es el mayor regalo de la vida.",
    "El camino al éxito se construye repetición tras repetición.",
    "No te compares con la persona que está a tu lado, sino con la que fuiste ayer.",
    "El entrenamiento es el mejor seguro de vida.",
    "La fuerza de tu cuerpo depende de la firmeza de tu mente.",
    "No hay atajos para los lugares a los que vale la pena ir.",
    "La perseverancia es el trabajo duro que haces después de cansarte del trabajo duro que ya hiciste. - Newt Gingrich",
    "Tu cuerpo es capaz de mucho más de lo que imaginas.",
    "El éxito no se encuentra al final, sino en cada paso del proceso.",
    "El entrenamiento diario es el alimento de tu salud.",
    "Sé constante y los resultados hablarán por sí solos.",
    "No dejes que los obstáculos te detengan; úsalos como escalones.",
    "La motivación es lo que te inicia, el hábito es lo que te mantiene.",
    "La verdadera fuerza reside en levantarse cuando los demás se rinden.",
    "Tu salud física es el reflejo de tu paz mental.",
    "Cada entrenamiento te prepara para el siguiente desafío.",
    "El gimnasio no es solo para el cuerpo, es para el alma.",
    "No busques milagros, busca hábitos saludables.",
    "La disciplina es el recordatorio diario de lo que realmente quieres.",
    "El éxito se construye con esfuerzo, dedicación y paciencia.",
    "Tus límites están en tu mente; rómpelos hoy.",
    "La constancia es la madre del éxito.",
    "Cada gota de sudor es un paso hacia tu meta.",
    "El cuerpo sano es el santuario del alma.",
    "No dejes que un mal día arruine tu constancia.",
    "El esfuerzo de hoy es la victoria del mañana.",
    "El entrenamiento es la mejor medicina preventiva.",
    "La mente es el límite; si tu mente puede verlo, puedes hacerlo.",
    "No te detengas hasta que estés orgulloso.",
    "La persistencia puede transformar el fracaso en un logro extraordinario. - Matt Biondi",
    "Tu cuerpo te lo agradecerá mañana.",
    "El éxito es la suma de pequeños esfuerzos diarios.",
    "El camino hacia la cima siempre es cuesta arriba.",
    "No dejes que la comodidad te aleje de tus metas.",
    "Cada repetición te hace más fuerte y más sabio.",
    "La disciplina es la base sobre la que se construye el éxito.",
    "Tu salud es tu mayor riqueza; no la descuides.",
    "La fuerza no es solo física, es la capacidad de resistir.",
    "El gimnasio es el laboratorio donde transformas tu cuerpo.",
    "No busques excusas para no entrenar, busca razones para hacerlo.",
    "La constancia en el entrenamiento es el secreto de la longevidad.",
    "Cada día es una oportunidad para superar tus marcas.",
    "El dolor es la forma en que el cuerpo te dice que estás progresando.",
    "La mente fuerte guía al cuerpo cansado.",
    "No dejes que la fatiga te venza; tú eres el dueño de tu esfuerzo.",
    "La autodisciplina es el secreto de los grandes logros.",
    "Tu cuerpo es el reflejo de tus decisiones diarias.",
    "El entrenamiento es una inversión a largo plazo en ti mismo.",
    "La perseverancia vence a la resistencia.",
    "El éxito llega a quienes tienen la paciencia de esperarlo y la fuerza de trabajar por él.",
    "Cada paso adelante es una victoria sobre la duda.",
    "La salud no es un destino, es una forma de vida.",
    "El gimnasio es el lugar donde los retos se convierten en logros.",
    "No te rindas cuando el camino se ponga difícil; es cuando más importa.",
    "La constancia es el ingrediente secreto de cualquier transformación.",
    "Tu cuerpo es tu templo; trátalo con respeto.",
    "El esfuerzo diario es la clave del progreso continuo.",
    "La disciplina te mantiene enfocado en tus metas a largo plazo.",
    "El éxito es el resultado directo de la consistencia.",
    "Cada entrenamiento es un compromiso contigo mismo.",
    "La fuerza mental es tu mayor aliado en el gimnasio.",
    "No dejes que la rutina apague tu pasión por el fitness.",
    "El cuerpo humano está diseñado para el movimiento; muévete hoy.",
    "La perseverancia es la clave para superar cualquier obstáculo.",
    "Tu salud es la inversión más rentable que jamás harás.",
    "Cada repetición es un paso más hacia tu objetivo final.",
    "El gimnasio es donde fortaleces tu cuerpo y tu carácter.",
    "No te conformes con menos de lo que puedes dar.",
    "La constancia es el puente hacia la excelencia física.",
    "El esfuerzo de hoy determina el rendimiento del mañana.",
    "La disciplina es el camino más rápido hacia tus metas.",
    "Tu cuerpo es la máquina más perfecta; mantenla en marcha.",
    "No dejes que las excusas dicten tu futuro físico.",
    "Cada día es una nueva página en tu diario de entrenamiento.",
    "La fuerza reside en la perseverancia y la dedicación.",
    "El gimnasio es el refugio donde te reencuentras con tu fuerza.",
    "No busques el éxito rápido; busca el cambio duradero.",
    "La consistencia es la base de todo logro físico.",
    "Tu salud es tu prioridad número uno; actúa en consecuencia.",
    "Cada sesión de entrenamiento te hace más resistente.",
    "La autodisciplina es el mayor acto de libertad.",
    "El cuerpo se fortalece con el uso; no lo dejes oxidar.",
    "No te rindas ante el cansancio; es solo una señal de esfuerzo.",
    "La constancia es lo que separa a los soñadores de los realizadores.",
    "El esfuerzo que haces hoy es la base de tu bienestar mañana.",
    "La disciplina es la llave que abre el potencial de tu cuerpo.",
    "Tu cuerpo es tu carta de presentación; cuídala con esmero.",
    "No dejes que un obstáculo temporal detenga tu progreso a largo plazo.",
    "Cada entrenamiento es una lección de superación personal.",
    "La fuerza de voluntad es la energía que mueve tus músculos.",
    "El gimnasio es el espacio donde desafías tus propios límites.",
    "No busques el camino sin dolor; busca el camino que te fortalezca.",
    "La consistencia es el motor de cualquier gran resultado.",
    "Tu salud es el cimiento de todos tus proyectos de vida.",
    "Cada repetición bien hecha es una victoria sobre la gravedad.",
    "La disciplina te define más que tu talento.",
    "El cuerpo se adapta a lo que le exiges; exígele lo mejor.",
    "No dejes que la pereza robe tus metas de salud.",
    "La constancia es la mejor estrategia para el éxito a largo plazo.",
    "El esfuerzo de hoy es la salud del mañana.",
    "La fuerza mental es la que te mantiene de pie cuando el cuerpo quiere sentarse.",
    "El gimnasio es el lugar donde demuestras tu compromiso contigo mismo.",
    "No busques excusas baratas; invierte en esfuerzos valiosos.",
    "La consistencia en el gimnasio se traduce en consistencia en la vida.",
    "Tu cuerpo es tu responsabilidad; trátalo como tal.",
    "Cada entrenamiento te acerca más a la persona que quieres ser.",
    "La disciplina es la forma más pura de respeto hacia ti mismo.",
    "El éxito físico requiere constancia, no perfección.",
    "No dejes que la impaciencia destruya tu progreso constante.",
    "Cada paso en el entrenamiento es un avance en tu salud.",
    "La fuerza no se regala, se gana con sudor y esfuerzo.",
    "El gimnasio es el templo donde se forja la perseverancia.",
    "No busques atajos; el camino largo te hace más fuerte.",
    "La consistencia es el secreto peor guardado del éxito.",
    "Tu salud es tu mayor activo; protégela con tu esfuerzo.",
    "Cada entrenamiento es una oportunidad para demostrar tu valía.",
    "La autodisciplina es el combustible del rendimiento.",
    "El cuerpo humano responde al esfuerzo continuo; no te detengas.",
    "No dejes que un tropiezo se convierta en una caída permanente.",
    "La constancia es la marca de un verdadero profesional de su salud.",
    "El esfuerzo diario es la inversión que nunca se pierde.",
    "La disciplina es el hábito de cumplir tus promesas.",
    "Tu cuerpo es capaz de adaptarse a cualquier desafío físico.",
    "No permitas que las excusas apaguen tus ganas de mejorar.",
    "Cada día de entrenamiento es un depósito en tu banco de salud.",
    "La fuerza se construye día a día, repetición a repetición.",
    "El gimnasio es el lugar donde los límites se desvanecen.",
    "No busques la aprobación de los demás; busca tu propio progreso.",
    "La consistencia es el pilar de cualquier programa de entrenamiento.",
    "Tu salud física es el motor de tu energía diaria.",
    "Cada repetición te enseña a superar la incomodidad.",
    "La disciplina te da el control sobre tu propio destino.",
    "El éxito en el fitness es una maratón, no un sprint.",
    "No dejes que un mal entrenamiento defina tu semana.",
    "La constancia es el imán que atrae los resultados positivos.",
    "El esfuerzo de hoy es la base de tu vitalidad mañana.",
    "La fuerza no es solo levantar peso, es mantener la constancia.",
    "El gimnasio es donde entrenas tu cuerpo y liberas tu mente.",
    "No te compares con nadie; tú eres tu propio estándar de éxito.",
    "La consistencia es el camino más directo hacia tu meta.",
    "Tu cuerpo es el vehículo de tu vida; dale el mejor combustible.",
    "Cada entrenamiento te ayuda a descubrir de lo que eres capaz.",
    "La disciplina es el puente entre la intención y la acción.",
    "El progreso físico es la recompensa de la constancia.",
    "No dejes que el cansancio nuble tus metas de largo plazo.",
    "La fuerza de voluntad se entrena igual que un músculo.",
    "El gimnasio es el escenario de tus victorias diarias.",
    "No busques resultados inmediatos; valora el progreso gradual.",
    "La consistencia es la clave para transformar tu cuerpo y tu mente.",
    "Tu salud es tu tesoro; invierte tiempo en protegerla.",
    "Cada repetición cuenta en la construcción de tu mejor versión.",
    "La autodisciplina es la base de toda verdadera confianza.",
    "El cuerpo humano es una obra de arte en constante evolución.",
    "No dejes que las opiniones ajenas detengan tu camino de salud.",
    "La constancia en el entrenamiento es el mejor hábito que puedes crear.",
    "El esfuerzo diario te da la energía para afrontar cualquier reto.",
    "La disciplina es el secreto de los resultados extraordinarios.",
    "Tu cuerpo es el reflejo directo de tus hábitos diarios.",
    "Cada sesión de entrenamiento es una inversión segura en tu futuro.",
    "La fuerza mental te permite superar cualquier meseta física.",
    "El gimnasio es donde pones a prueba tu determinación.",
    "No busques el camino sin esfuerzo; busca el camino que valga la pena.",
    "La consistencia es la diferencia entre desear y lograr.",
    "Tu salud es la base de tu felicidad; cuídala cada día.",
    "Cada repetición te acerca un paso más a tu objetivo.",
    "La disciplina es la forma en que demuestras que te valoras.",
    "El éxito en el fitness se logra con paciencia y constancia.",
    "No dejes que el desánimo temporal detenga tu progreso a largo plazo.",
    "La constancia es la clave para desbloquear tu potencial físico.",
    "El esfuerzo de hoy es la tranquilidad de mañana.",
    "La fuerza no se mide en kilogramos, sino en determinación.",
    "El gimnasio es el espacio donde te superas a ti mismo cada día.",
    "No busques excusas para faltar; busca motivos para asistir.",
    "La consistencia es el lenguaje en el que tu cuerpo entiende el cambio.",
    "Tu cuerpo es tu único hogar permanente; mantenlo fuerte.",
    "Cada entrenamiento es una oportunidad para ser mejor que ayer.",
    "La disciplina te ayuda a superar la falta de motivación.",
    "El éxito en el entrenamiento es la recompensa de la persistencia.",
    "No dejes que un obstáculo en el camino te haga olvidar tu destino.",
    "La constancia es el pegamento que une tus metas con tus logros.",
    "El esfuerzo diario es el camino más seguro hacia la excelencia.",
    "La fuerza de voluntad es la llave de tu transformación física.",
    "El gimnasio es el lugar donde el esfuerzo se convierte en resultados.",
    "No busques atajos fáciles; el esfuerzo es lo que te da valor.",
    "La consistencia es el motor que impulsa tu evolución física.",
    "Tu salud es tu mayor patrimonio; invierte en ella cada día.",
    "Cada repetición es un ladrillo en la construcción de tu fuerza.",
    "La autodisciplina es la que te mantiene firme en tu camino.",
    "El cuerpo responde al estímulo continuo; sé constante.",
    "No dejes que el cansancio de un día detenga tu programa de salud.",
    "La constancia es el secreto para alcanzar cualquier meta física.",
    "El esfuerzo que haces hoy es la salud de la que disfrutarás mañana.",
    "La disciplina es la herramienta más poderosa para tu desarrollo.",
    "Tu cuerpo es capaz de superar cualquier límite que le impongas.",
    "No permitas que la comodidad sabotee tus objetivos de salud.",
    "Cada día de entrenamiento es una victoria sobre la rutina.",
    "La fuerza se cultiva con paciencia, sudor y constancia.",
    "El gimnasio es el taller donde rediseñas tu cuerpo.",
    "No busques compararte con otros; compite contra tus marcas.",
    "La consistencia es el pilar fundamental del entrenamiento exitoso.",
    "Tu salud física es el motor de tu bienestar mental.",
    "Cada repetición te enseña el valor de la perseverancia.",
    "La disciplina es la brújula que te guía hacia tus metas.",
    "El éxito en el fitness no es un evento, es un estilo de vida.",
    "No dejes que los pequeños tropiezos te desvíen de tu gran meta.",
    "La constancia es el factor clave para cualquier cambio duradero.",
    "El esfuerzo diario es la semilla de tus futuros logros.",
    "La fuerza mental es el escudo que te protege de la pereza.",
    "El gimnasio es donde dejas las palabras y demuestras con hechos.",
    "No busques excusas; el tiempo para entrenar se crea.",
    "La consistencia en tus hábitos de entrenamiento es tu mejor aliada.",
    "Tu cuerpo es tu templo; no permitas que se debilite.",
    "Cada entrenamiento es un paso adelante en tu camino de salud.",
    "La disciplina es el hábito de cumplir contigo mismo.",
    "El éxito físico es el resultado de la perseverancia diaria.",
    "No dejes que la falta de tiempo sea el freno de tu salud.",
    "La constancia es la clave para mantener tus resultados a largo plazo.",
    "El esfuerzo que pones hoy es la energía que tendrás mañana.",
    "La fuerza no se improvisa, se construye con cada entrenamiento.",
    "El gimnasio es el espacio donde forjas una mente indestructible.",
    "No busques el éxito sin sudor; el sudor es parte del logro.",
    "La consistencia es el camino que transforma el esfuerzo en hábito.",
    "Tu salud es tu activo más valioso; entrénala a diario.",
    "Cada repetición te acerca más a tu meta de bienestar.",
    "La disciplina te sostiene cuando la motivación se apaga.",
    "El éxito es la constancia aplicada a tus metas de salud.",
    "No te detengas hasta que el esfuerzo se convierta en satisfacción.",
    "La perseverancia es el secreto para dominar cualquier ejercicio.",
    "Tu cuerpo tiene memoria; dale buenos hábitos físicos.",
    "Cada día es una oportunidad para ser el dueño de tu salud.",
    "La fuerza reside en la decisión de no rendirse nunca.",
    "El gimnasio es tu zona de poder; aprovéchala.",
    "No busques resultados rápidos; valora la salud para toda la vida.",
    "La consistencia es el puente entre el esfuerzo y el resultado.",
    "Tu salud es tu mejor carta de presentación; cuídala hoy.",
    "Cada entrenamiento es un peldaño en tu escalera hacia el éxito.",
    "La disciplina es la base de toda verdadera transformación física.",
    "El éxito comienza cuando decides ser más grande que tus excusas.",
    "La verdadera fuerza es la que sonríe ante la adversidad.",
    "Cada paso te acerca más a la cima del éxito físico.",
    "No midas tu progreso con la regla de otros.",
    "Tu cuerpo es el reflejo de tus elecciones diarias.",
    "La disciplina es el puente que te lleva de los deseos a la realidad.",
    "El gimnasio no solo fortalece tus músculos, también tu carácter.",
    "No cuentes los entrenamientos, haz que cada entrenamiento cuente.",
    "La salud es la base de todo lo que puedes lograr en la vida.",
    "Haz del ejercicio una parte innegociable de tu día.",
    "No busques excusas para parar; busca razones para continuar.",
    "El dolor de la disciplina es menor que el dolor del arrepentimiento.",
    "Tu mente controla tu cuerpo, dale órdenes de superación.",
    "Cada día es una oportunidad de oro para esculpir tu mejor versión.",
    "La consistencia diaria derrota al talento ocasional.",
    "No te detengas cuando te canses; descansa, y luego continúa.",
    "Tu entrenamiento es el momento en el que inviertes en ti.",
    "La constancia es el ingrediente invisible del éxito físico.",
    "El progreso ocurre fuera de tu zona de confort.",
    "No dejes que los días grises detengan tu brillo en el gimnasio.",
    "El hábito del ejercicio es el mejor regalo para tu futuro yo.",
    "La fuerza física es el resultado del coraje mental.",
    "Cada repetición cuenta para construir un físico de acero.",
    "La determinación es el motor que te impulsa en las últimas repeticiones.",
    "No busques la aprobación de los demás; supera tus propias marcas.",
    "La salud y la fuerza son recompensas que se ganan a diario.",
    "La disciplina convierte los sueños en metas alcanzables.",
    "Haz de cada sesión de entrenamiento un tributo a tu salud.",
    "La motivación es la chispa, pero el hábito es la llama que arde.",
    "No te rindas cuando el camino se ponga cuesta arriba; es señal de crecimiento.",
    "La constancia vence a cualquier obstáculo que se interponga.",
    "Tu esfuerzo de hoy define el bienestar que sentirás mañana.",
    "El gimnasio es el laboratorio donde pones a prueba tu fuerza de voluntad.",
    "La perseverancia transforma las dificultades en oportunidades de mejora.",
    "Tu cuerpo es tu máquina más perfecta, dale el mantenimiento que merece.",
    "Cada gota de sudor es un paso adelante hacia tu meta.",
    "La disciplina es el secreto mejor guardado de los campeones.",
    "No busques el camino corto; el camino del esfuerzo te hace fuerte.",
    "La consistencia es el cemento que une tus sueños con tu realidad.",
    "Tu cuerpo es el reflejo de tu disciplina y constancia diaria."
];
